package com.edusasse.lfpa.gals;

public interface Constants extends ScannerConstants, ParserConstants {
    public static final int DOLLAR = 1;
    public static final int EPSILON = 0;
    public static final int t_abreChaves = 33;
    public static final int t_abreParenteses = 31;
    public static final int t_acao_melhoria = 3;
    public static final int t_atualizacao_on_line = 13;
    public static final int t_complexidade_de_processamento = 14;
    public static final int t_comunicacao_de_dados = 6;
    public static final int t_configuracao_altamente_utilizada = 9;
    public static final int t_desenvol = 22;
    public static final int t_doisPontos = 28;
    public static final int t_eficiencia_do_usuario_final = 12;
    public static final int t_entrada_de_dados_on_line = 11;
    public static final int t_estende = 20;
    public static final int t_facilidade_de_instalacao = 16;
    public static final int t_facilidade_de_mudancas = 19;
    public static final int t_facilidade_de_operacao = 17;
    public static final int t_fechaChaves = 34;
    public static final int t_fechaParenteses = 32;
    public static final int t_int = 26;
    public static final int t_melhoria = 21;
    public static final int t_multiplas_localidades = 18;
    public static final int t_multiplicador = 27;
    public static final int t_origem = 2;
    public static final int t_performance = 8;
    public static final int t_pontoVirgula = 29;
    public static final int t_processamento_distribuido = 7;
    public static final int t_prog_nome = 24;
    public static final int t_proj_nome = 23;
    public static final int t_real = 5;
    public static final int t_reutilizacao = 15;
    public static final int t_taxa_de_transacoes = 10;
    public static final int t_texto = 25;
    public static final int t_variavel = 4;
    public static final int t_virgula = 30;
}
